// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tsjy.EntityFramework.Core;

#nullable disable

namespace Tsjy.Database.Migrations.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    [Migration("20251225192936_v20.0.0")]
    partial class v2000
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Tsjy.Core.Entities.AiPreEvaluation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("AnalysisReport")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("EvidenceId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("NodeId")
                        .HasColumnType("bigint");

                    b.Property<string>("RiskLevel")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("SuggestedScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("TaskId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("ai_pre_evaluations");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AnalysisReport = "AI分析通过",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 260, DateTimeKind.Utc).AddTicks(4959),
                            EvidenceId = 1L,
                            IsDeleted = false,
                            NodeId = 3L,
                            RiskLevel = "low",
                            SuggestedScore = 4.5m,
                            TaskId = 1L,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 260, DateTimeKind.Utc).AddTicks(4962),
                            UserId = 1L
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.Departments", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("IncSchoolsNum")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("OrgType")
                        .HasColumnType("int");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<string>("RegionCode")
                        .HasColumnType("longtext");

                    b.Property<long>("SpeSchoolsNum")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Code");

                    b.ToTable("departments");

                    b.HasData(
                        new
                        {
                            Code = "110000_EDU",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 203, DateTimeKind.Utc).AddTicks(3324),
                            IncSchoolsNum = 1000L,
                            IsDeleted = false,
                            Level = 0,
                            Name = "北京市教委",
                            OrgType = 2,
                            Phone = 0,
                            RegionCode = "110000",
                            SpeSchoolsNum = 20L,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 203, DateTimeKind.Utc).AddTicks(3326)
                        },
                        new
                        {
                            Code = "110105_EDU",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 203, DateTimeKind.Utc).AddTicks(4032),
                            IncSchoolsNum = 150L,
                            IsDeleted = false,
                            Level = 2,
                            Name = "朝阳区教委",
                            OrgType = 2,
                            Phone = 0,
                            RegionCode = "110105",
                            SpeSchoolsNum = 3L,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 203, DateTimeKind.Utc).AddTicks(4032)
                        },
                        new
                        {
                            Code = "110108_EDU",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 203, DateTimeKind.Utc).AddTicks(4034),
                            IncSchoolsNum = 180L,
                            IsDeleted = false,
                            Level = 2,
                            Name = "海淀区教委",
                            OrgType = 2,
                            Phone = 0,
                            RegionCode = "110108",
                            SpeSchoolsNum = 4L,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 203, DateTimeKind.Utc).AddTicks(4034)
                        },
                        new
                        {
                            Code = "130000_EDU",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 203, DateTimeKind.Utc).AddTicks(4035),
                            IncSchoolsNum = 3000L,
                            IsDeleted = false,
                            Level = 0,
                            Name = "河北省教育厅",
                            OrgType = 2,
                            Phone = 0,
                            RegionCode = "130000",
                            SpeSchoolsNum = 150L,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 203, DateTimeKind.Utc).AddTicks(4036)
                        },
                        new
                        {
                            Code = "130100_EDU",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 203, DateTimeKind.Utc).AddTicks(4037),
                            IncSchoolsNum = 200L,
                            IsDeleted = false,
                            Level = 1,
                            Name = "石家庄市教育局",
                            OrgType = 2,
                            Phone = 0,
                            RegionCode = "130100",
                            SpeSchoolsNum = 12L,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 203, DateTimeKind.Utc).AddTicks(4037)
                        },
                        new
                        {
                            Code = "130400_EDU",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 203, DateTimeKind.Utc).AddTicks(4041),
                            IncSchoolsNum = 180L,
                            IsDeleted = false,
                            Level = 1,
                            Name = "邯郸市教育局",
                            OrgType = 2,
                            Phone = 0,
                            RegionCode = "130400",
                            SpeSchoolsNum = 10L,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 203, DateTimeKind.Utc).AddTicks(4041)
                        },
                        new
                        {
                            Code = "110105_SPE_01",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 203, DateTimeKind.Utc).AddTicks(4042),
                            IncSchoolsNum = 0L,
                            IsDeleted = false,
                            Level = 2,
                            Name = "北京市朝阳区安华学校",
                            OrgType = 0,
                            Phone = 0,
                            RegionCode = "110105",
                            SpeSchoolsNum = 0L,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 203, DateTimeKind.Utc).AddTicks(4042)
                        },
                        new
                        {
                            Code = "110108_SPE_01",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 203, DateTimeKind.Utc).AddTicks(4043),
                            IncSchoolsNum = 0L,
                            IsDeleted = false,
                            Level = 2,
                            Name = "北京市海淀区特殊教育学校",
                            OrgType = 0,
                            Phone = 0,
                            RegionCode = "110108",
                            SpeSchoolsNum = 0L,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 203, DateTimeKind.Utc).AddTicks(4044)
                        },
                        new
                        {
                            Code = "130100_SPE_01",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 203, DateTimeKind.Utc).AddTicks(4045),
                            IncSchoolsNum = 0L,
                            IsDeleted = false,
                            Level = 1,
                            Name = "石家庄市特殊教育学校",
                            OrgType = 0,
                            Phone = 0,
                            RegionCode = "130100",
                            SpeSchoolsNum = 0L,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 203, DateTimeKind.Utc).AddTicks(4045)
                        },
                        new
                        {
                            Code = "130102_SPE_01",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 203, DateTimeKind.Utc).AddTicks(4047),
                            IncSchoolsNum = 0L,
                            IsDeleted = false,
                            Level = 2,
                            Name = "石家庄市长安区启智学校",
                            OrgType = 0,
                            Phone = 0,
                            RegionCode = "130102",
                            SpeSchoolsNum = 0L,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 203, DateTimeKind.Utc).AddTicks(4047)
                        },
                        new
                        {
                            Code = "130400_SPE_01",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 203, DateTimeKind.Utc).AddTicks(4048),
                            IncSchoolsNum = 0L,
                            IsDeleted = false,
                            Level = 1,
                            Name = "邯郸市特殊教育中心",
                            OrgType = 0,
                            Phone = 0,
                            RegionCode = "130400",
                            SpeSchoolsNum = 0L,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 203, DateTimeKind.Utc).AddTicks(4048)
                        },
                        new
                        {
                            Code = "110105_INC_01",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 203, DateTimeKind.Utc).AddTicks(4049),
                            IncSchoolsNum = 0L,
                            IsDeleted = false,
                            Level = 2,
                            Name = "朝阳区实验小学",
                            OrgType = 1,
                            Phone = 0,
                            RegionCode = "110105",
                            SpeSchoolsNum = 0L,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 203, DateTimeKind.Utc).AddTicks(4049)
                        },
                        new
                        {
                            Code = "110108_INC_01",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 203, DateTimeKind.Utc).AddTicks(4050),
                            IncSchoolsNum = 0L,
                            IsDeleted = false,
                            Level = 2,
                            Name = "中关村第一小学",
                            OrgType = 1,
                            Phone = 0,
                            RegionCode = "110108",
                            SpeSchoolsNum = 0L,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 203, DateTimeKind.Utc).AddTicks(4051)
                        },
                        new
                        {
                            Code = "130104_INC_01",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 203, DateTimeKind.Utc).AddTicks(4052),
                            IncSchoolsNum = 0L,
                            IsDeleted = false,
                            Level = 2,
                            Name = "石家庄草场街小学",
                            OrgType = 1,
                            Phone = 0,
                            RegionCode = "130104",
                            SpeSchoolsNum = 0L,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 203, DateTimeKind.Utc).AddTicks(4052)
                        },
                        new
                        {
                            Code = "130402_INC_01",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 203, DateTimeKind.Utc).AddTicks(4053),
                            IncSchoolsNum = 0L,
                            IsDeleted = false,
                            Level = 2,
                            Name = "邯郸市邯山区实验小学",
                            OrgType = 1,
                            Phone = 0,
                            RegionCode = "130402",
                            SpeSchoolsNum = 0L,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 203, DateTimeKind.Utc).AddTicks(4053)
                        },
                        new
                        {
                            Code = "110000_OTH_01",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 203, DateTimeKind.Utc).AddTicks(4054),
                            IncSchoolsNum = 0L,
                            IsDeleted = false,
                            Level = 0,
                            Name = "北师大特教研究所",
                            OrgType = 3,
                            Phone = 0,
                            RegionCode = "110000",
                            SpeSchoolsNum = 0L,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 203, DateTimeKind.Utc).AddTicks(4054)
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.DistributionBatch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DueAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("InspectionEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("InspectionStart")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("ReviewEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ReviewStart")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TargetType")
                        .HasColumnType("int");

                    b.Property<long>("TreeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UploadEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UploadStart")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("distribution_batches");

                    b.HasData(
                        new
                        {
                            Id = 10000L,
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 273, DateTimeKind.Utc).AddTicks(414),
                            DueAt = new DateTime(2026, 1, 14, 19, 29, 36, 273, DateTimeKind.Utc).AddTicks(1081),
                            IsDeleted = false,
                            Name = "2025年特教学校春季普查",
                            StartAt = new DateTime(2025, 12, 15, 19, 29, 36, 273, DateTimeKind.Utc).AddTicks(888),
                            Status = 2,
                            TargetType = 0,
                            TreeId = 202501L,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 273, DateTimeKind.Utc).AddTicks(415)
                        },
                        new
                        {
                            Id = 10001L,
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 273, DateTimeKind.Utc).AddTicks(1167),
                            DueAt = new DateTime(2026, 1, 29, 19, 29, 36, 273, DateTimeKind.Utc).AddTicks(1170),
                            IsDeleted = false,
                            Name = "海淀区随班就读质量监测",
                            StartAt = new DateTime(2025, 12, 30, 19, 29, 36, 273, DateTimeKind.Utc).AddTicks(1169),
                            Status = 0,
                            TargetType = 0,
                            TreeId = 202502L,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 273, DateTimeKind.Utc).AddTicks(1168)
                        },
                        new
                        {
                            Id = 10002L,
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 273, DateTimeKind.Utc).AddTicks(1171),
                            DueAt = new DateTime(2026, 1, 9, 19, 29, 36, 273, DateTimeKind.Utc).AddTicks(1172),
                            IsDeleted = false,
                            Name = "2025区域特教发展绩效评价",
                            StartAt = new DateTime(2025, 12, 23, 19, 29, 36, 273, DateTimeKind.Utc).AddTicks(1172),
                            Status = 2,
                            TargetType = 0,
                            TreeId = 202503L,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 273, DateTimeKind.Utc).AddTicks(1171)
                        },
                        new
                        {
                            Id = 10003L,
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 273, DateTimeKind.Utc).AddTicks(1173),
                            DueAt = new DateTime(2025, 1, 24, 19, 29, 36, 273, DateTimeKind.Utc).AddTicks(1192),
                            IsDeleted = false,
                            Name = "2024年终考核存档",
                            StartAt = new DateTime(2024, 12, 25, 19, 29, 36, 273, DateTimeKind.Utc).AddTicks(1174),
                            Status = 3,
                            TargetType = 0,
                            TreeId = 202401L,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 273, DateTimeKind.Utc).AddTicks(1173)
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.EduEvalNode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Depth")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("MaxScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Path")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<long?>("ScoringTemplateId")
                        .HasColumnType("bigint");

                    b.Property<long>("TreeId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("edu_eval_nodes");

                    b.HasData(
                        new
                        {
                            Id = 30000L,
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 255, DateTimeKind.Utc).AddTicks(3346),
                            Depth = 0,
                            IsDeleted = false,
                            MaxScore = 100m,
                            Name = "2025区域特教发展评价",
                            OrderIndex = 0,
                            Path = "0",
                            TreeId = 202503L,
                            Type = 0,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 255, DateTimeKind.Utc).AddTicks(3348)
                        },
                        new
                        {
                            Id = 30001L,
                            Code = "1",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 255, DateTimeKind.Utc).AddTicks(4238),
                            Depth = 1,
                            IsDeleted = false,
                            MaxScore = 60m,
                            Name = "经费保障",
                            OrderIndex = 0,
                            ParentId = 30000L,
                            Path = "0,30000",
                            TreeId = 202503L,
                            Type = 1,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 255, DateTimeKind.Utc).AddTicks(4238)
                        },
                        new
                        {
                            Id = 30002L,
                            Code = "1.1",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 255, DateTimeKind.Utc).AddTicks(4332),
                            Depth = 2,
                            IsDeleted = false,
                            MaxScore = 60m,
                            Name = "生均公用经费标准",
                            OrderIndex = 0,
                            ParentId = 30001L,
                            Path = "0,30000,30001",
                            ScoringTemplateId = 1L,
                            TreeId = 202503L,
                            Type = 4,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 255, DateTimeKind.Utc).AddTicks(4332)
                        },
                        new
                        {
                            Id = 30003L,
                            Code = "2",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 255, DateTimeKind.Utc).AddTicks(4423),
                            Depth = 1,
                            IsDeleted = false,
                            MaxScore = 40m,
                            Name = "入学率",
                            OrderIndex = 0,
                            ParentId = 30000L,
                            Path = "0,30000",
                            TreeId = 202503L,
                            Type = 1,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 255, DateTimeKind.Utc).AddTicks(4423)
                        },
                        new
                        {
                            Id = 30004L,
                            Code = "2.1",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 255, DateTimeKind.Utc).AddTicks(4427),
                            Depth = 2,
                            IsDeleted = false,
                            MaxScore = 40m,
                            Name = "义务教育入学率",
                            OrderIndex = 0,
                            ParentId = 30003L,
                            Path = "0,30000,30003",
                            ScoringTemplateId = 1L,
                            TreeId = 202503L,
                            Type = 4,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 255, DateTimeKind.Utc).AddTicks(4427)
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.ExpertReview", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("FinalScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("NodeId")
                        .HasColumnType("bigint");

                    b.Property<string>("ReviewerId")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("ScoreRatio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("StandardScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("TaskId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("TaskId");

                    b.HasIndex("ReviewerId", "Status");

                    b.ToTable("expert_reviews");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 263, DateTimeKind.Utc).AddTicks(4429),
                            FinalScore = 4.0m,
                            IsDeleted = false,
                            NodeId = 3L,
                            ReviewerId = "100",
                            ScoreRatio = 0.8m,
                            StandardScore = 5m,
                            Status = 0,
                            TaskId = 1L,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 263, DateTimeKind.Utc).AddTicks(3714)
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.IncEvalNode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Depth")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("MaxScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Path")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<long?>("ScoringTemplateId")
                        .HasColumnType("bigint");

                    b.Property<long>("TreeId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("inc_eval_nodes");

                    b.HasData(
                        new
                        {
                            Id = 20000L,
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 253, DateTimeKind.Utc).AddTicks(8656),
                            Depth = 0,
                            IsDeleted = false,
                            MaxScore = 100m,
                            Name = "2025随班就读质量监测",
                            OrderIndex = 0,
                            Path = "0",
                            TreeId = 202502L,
                            Type = 0,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 253, DateTimeKind.Utc).AddTicks(8658)
                        },
                        new
                        {
                            Id = 20001L,
                            Code = "1",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 253, DateTimeKind.Utc).AddTicks(9589),
                            Depth = 1,
                            IsDeleted = false,
                            MaxScore = 50m,
                            Name = "资源教室",
                            OrderIndex = 0,
                            ParentId = 20000L,
                            Path = "0,20000",
                            TreeId = 202502L,
                            Type = 1,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 253, DateTimeKind.Utc).AddTicks(9589)
                        },
                        new
                        {
                            Id = 20002L,
                            Code = "1.1",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 253, DateTimeKind.Utc).AddTicks(9688),
                            Depth = 2,
                            IsDeleted = false,
                            MaxScore = 25m,
                            Name = "资源教师配备",
                            OrderIndex = 0,
                            ParentId = 20001L,
                            Path = "0,20000,20001",
                            ScoringTemplateId = 2L,
                            TreeId = 202502L,
                            Type = 4,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 253, DateTimeKind.Utc).AddTicks(9688)
                        },
                        new
                        {
                            Id = 20003L,
                            Code = "1.2",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 253, DateTimeKind.Utc).AddTicks(9779),
                            Depth = 2,
                            IsDeleted = false,
                            MaxScore = 25m,
                            Name = "设备使用率",
                            OrderIndex = 0,
                            ParentId = 20001L,
                            Path = "0,20000,20001",
                            ScoringTemplateId = 1L,
                            TreeId = 202502L,
                            Type = 4,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 253, DateTimeKind.Utc).AddTicks(9780)
                        },
                        new
                        {
                            Id = 20004L,
                            Code = "2",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 253, DateTimeKind.Utc).AddTicks(9784),
                            Depth = 1,
                            IsDeleted = false,
                            MaxScore = 50m,
                            Name = "融合文化",
                            OrderIndex = 0,
                            ParentId = 20000L,
                            Path = "0,20000",
                            TreeId = 202502L,
                            Type = 1,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 253, DateTimeKind.Utc).AddTicks(9784)
                        },
                        new
                        {
                            Id = 20005L,
                            Code = "2.1",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 253, DateTimeKind.Utc).AddTicks(9789),
                            Depth = 2,
                            IsDeleted = false,
                            MaxScore = 50m,
                            Name = "普特融合活动",
                            OrderIndex = 0,
                            ParentId = 20004L,
                            Path = "0,20000,20004",
                            ScoringTemplateId = 1L,
                            TreeId = 202502L,
                            Type = 4,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 253, DateTimeKind.Utc).AddTicks(9789)
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.Region", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ParentCode")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Code");

                    b.ToTable("regions");

                    b.HasData(
                        new
                        {
                            Code = "110000",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(7497),
                            IsDeleted = false,
                            Level = 0,
                            Name = "北京市",
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(7501)
                        },
                        new
                        {
                            Code = "110101",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8083),
                            IsDeleted = false,
                            Level = 2,
                            Name = "东城区",
                            ParentCode = "110000",
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8083)
                        },
                        new
                        {
                            Code = "110102",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8085),
                            IsDeleted = false,
                            Level = 2,
                            Name = "西城区",
                            ParentCode = "110000",
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8085)
                        },
                        new
                        {
                            Code = "110105",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8085),
                            IsDeleted = false,
                            Level = 2,
                            Name = "朝阳区",
                            ParentCode = "110000",
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8086)
                        },
                        new
                        {
                            Code = "110106",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8086),
                            IsDeleted = false,
                            Level = 2,
                            Name = "丰台区",
                            ParentCode = "110000",
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8086)
                        },
                        new
                        {
                            Code = "110107",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8092),
                            IsDeleted = false,
                            Level = 2,
                            Name = "石景山区",
                            ParentCode = "110000",
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8092)
                        },
                        new
                        {
                            Code = "110108",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8093),
                            IsDeleted = false,
                            Level = 2,
                            Name = "海淀区",
                            ParentCode = "110000",
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8093)
                        },
                        new
                        {
                            Code = "110109",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8093),
                            IsDeleted = false,
                            Level = 2,
                            Name = "门头沟区",
                            ParentCode = "110000",
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8094)
                        },
                        new
                        {
                            Code = "110111",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8094),
                            IsDeleted = false,
                            Level = 2,
                            Name = "房山区",
                            ParentCode = "110000",
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8094)
                        },
                        new
                        {
                            Code = "110112",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8095),
                            IsDeleted = false,
                            Level = 2,
                            Name = "通州区",
                            ParentCode = "110000",
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8095)
                        },
                        new
                        {
                            Code = "110113",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8096),
                            IsDeleted = false,
                            Level = 2,
                            Name = "顺义区",
                            ParentCode = "110000",
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8096)
                        },
                        new
                        {
                            Code = "110114",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8097),
                            IsDeleted = false,
                            Level = 2,
                            Name = "昌平区",
                            ParentCode = "110000",
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8097)
                        },
                        new
                        {
                            Code = "110115",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8097),
                            IsDeleted = false,
                            Level = 2,
                            Name = "大兴区",
                            ParentCode = "110000",
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8097)
                        },
                        new
                        {
                            Code = "110116",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8098),
                            IsDeleted = false,
                            Level = 2,
                            Name = "怀柔区",
                            ParentCode = "110000",
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8098)
                        },
                        new
                        {
                            Code = "110117",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8098),
                            IsDeleted = false,
                            Level = 2,
                            Name = "平谷区",
                            ParentCode = "110000",
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8099)
                        },
                        new
                        {
                            Code = "110118",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8099),
                            IsDeleted = false,
                            Level = 2,
                            Name = "密云区",
                            ParentCode = "110000",
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8099)
                        },
                        new
                        {
                            Code = "110119",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8100),
                            IsDeleted = false,
                            Level = 2,
                            Name = "延庆区",
                            ParentCode = "110000",
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8100)
                        },
                        new
                        {
                            Code = "130000",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8111),
                            IsDeleted = false,
                            Level = 0,
                            Name = "河北省",
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8111)
                        },
                        new
                        {
                            Code = "130100",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8163),
                            IsDeleted = false,
                            Level = 1,
                            Name = "石家庄市",
                            ParentCode = "130000",
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8163)
                        },
                        new
                        {
                            Code = "130102",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8164),
                            IsDeleted = false,
                            Level = 2,
                            Name = "长安区",
                            ParentCode = "130100",
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8165)
                        },
                        new
                        {
                            Code = "130200",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8166),
                            IsDeleted = false,
                            Level = 1,
                            Name = "唐山市",
                            ParentCode = "130000",
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8166)
                        },
                        new
                        {
                            Code = "130202",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8166),
                            IsDeleted = false,
                            Level = 2,
                            Name = "路南区",
                            ParentCode = "130200",
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8166)
                        },
                        new
                        {
                            Code = "130300",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8167),
                            IsDeleted = false,
                            Level = 1,
                            Name = "秦皇岛市",
                            ParentCode = "130000",
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8167)
                        },
                        new
                        {
                            Code = "130302",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8168),
                            IsDeleted = false,
                            Level = 2,
                            Name = "海港区",
                            ParentCode = "130300",
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8168)
                        },
                        new
                        {
                            Code = "130400",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8168),
                            IsDeleted = false,
                            Level = 1,
                            Name = "邯郸市",
                            ParentCode = "130000",
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8169)
                        },
                        new
                        {
                            Code = "130402",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8169),
                            IsDeleted = false,
                            Level = 2,
                            Name = "邯山区",
                            ParentCode = "130400",
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8169)
                        },
                        new
                        {
                            Code = "130500",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8169),
                            IsDeleted = false,
                            Level = 1,
                            Name = "邢台市",
                            ParentCode = "130000",
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8170)
                        },
                        new
                        {
                            Code = "130502",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8170),
                            IsDeleted = false,
                            Level = 2,
                            Name = "襄都区",
                            ParentCode = "130500",
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8170)
                        },
                        new
                        {
                            Code = "130600",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8171),
                            IsDeleted = false,
                            Level = 1,
                            Name = "保定市",
                            ParentCode = "130000",
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8171)
                        },
                        new
                        {
                            Code = "130606",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8171),
                            IsDeleted = false,
                            Level = 2,
                            Name = "莲池区",
                            ParentCode = "130600",
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8172)
                        },
                        new
                        {
                            Code = "130700",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8172),
                            IsDeleted = false,
                            Level = 1,
                            Name = "张家口市",
                            ParentCode = "130000",
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8172)
                        },
                        new
                        {
                            Code = "130702",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8173),
                            IsDeleted = false,
                            Level = 2,
                            Name = "桥东区",
                            ParentCode = "130700",
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8173)
                        },
                        new
                        {
                            Code = "130800",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8173),
                            IsDeleted = false,
                            Level = 1,
                            Name = "承德市",
                            ParentCode = "130000",
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8173)
                        },
                        new
                        {
                            Code = "130802",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8176),
                            IsDeleted = false,
                            Level = 2,
                            Name = "双桥区",
                            ParentCode = "130800",
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8176)
                        },
                        new
                        {
                            Code = "130900",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8177),
                            IsDeleted = false,
                            Level = 1,
                            Name = "沧州市",
                            ParentCode = "130000",
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8177)
                        },
                        new
                        {
                            Code = "130902",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8178),
                            IsDeleted = false,
                            Level = 2,
                            Name = "新华区",
                            ParentCode = "130900",
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8178)
                        },
                        new
                        {
                            Code = "131000",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8178),
                            IsDeleted = false,
                            Level = 1,
                            Name = "廊坊市",
                            ParentCode = "130000",
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8179)
                        },
                        new
                        {
                            Code = "131003",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8179),
                            IsDeleted = false,
                            Level = 2,
                            Name = "广阳区",
                            ParentCode = "131000",
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8179)
                        },
                        new
                        {
                            Code = "131100",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8180),
                            IsDeleted = false,
                            Level = 1,
                            Name = "衡水市",
                            ParentCode = "130000",
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8180)
                        },
                        new
                        {
                            Code = "131102",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8180),
                            IsDeleted = false,
                            Level = 2,
                            Name = "桃城区",
                            ParentCode = "131100",
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 199, DateTimeKind.Utc).AddTicks(8180)
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.ScoringModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("scoring_templates");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 12, 26, 3, 29, 36, 245, DateTimeKind.Local).AddTicks(9331),
                            IsDeleted = false,
                            Name = "四级评分(A/B/C/D)",
                            UpdatedAt = new DateTime(2025, 12, 26, 3, 29, 36, 248, DateTimeKind.Local).AddTicks(390)
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2025, 12, 26, 3, 29, 36, 248, DateTimeKind.Local).AddTicks(998),
                            IsDeleted = false,
                            Name = "是否合格(是/否)",
                            UpdatedAt = new DateTime(2025, 12, 26, 3, 29, 36, 248, DateTimeKind.Local).AddTicks(1000)
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2025, 12, 26, 3, 29, 36, 248, DateTimeKind.Local).AddTicks(1001),
                            IsDeleted = false,
                            Name = "五星评价(1-5星)",
                            UpdatedAt = new DateTime(2025, 12, 26, 3, 29, 36, 248, DateTimeKind.Local).AddTicks(1001)
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.ScoringModelItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LevelCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("Ratio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("ScoringModelId")
                        .HasColumnType("bigint");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<long>("TemplateId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ScoringModelId");

                    b.ToTable("scoring_template_items");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 12, 26, 3, 29, 36, 248, DateTimeKind.Local).AddTicks(9404),
                            Description = "完全符合",
                            IsDeleted = false,
                            LevelCode = "A",
                            Ratio = 1.0m,
                            Sort = 1,
                            TemplateId = 1L,
                            UpdatedAt = new DateTime(2025, 12, 26, 3, 29, 36, 248, DateTimeKind.Local).AddTicks(9407)
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2025, 12, 26, 3, 29, 36, 249, DateTimeKind.Local).AddTicks(131),
                            Description = "基本符合",
                            IsDeleted = false,
                            LevelCode = "B",
                            Ratio = 0.8m,
                            Sort = 2,
                            TemplateId = 1L,
                            UpdatedAt = new DateTime(2025, 12, 26, 3, 29, 36, 249, DateTimeKind.Local).AddTicks(132)
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2025, 12, 26, 3, 29, 36, 249, DateTimeKind.Local).AddTicks(133),
                            Description = "部分符合",
                            IsDeleted = false,
                            LevelCode = "C",
                            Ratio = 0.6m,
                            Sort = 3,
                            TemplateId = 1L,
                            UpdatedAt = new DateTime(2025, 12, 26, 3, 29, 36, 249, DateTimeKind.Local).AddTicks(134)
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2025, 12, 26, 3, 29, 36, 249, DateTimeKind.Local).AddTicks(135),
                            Description = "不符合",
                            IsDeleted = false,
                            LevelCode = "D",
                            Ratio = 0.0m,
                            Sort = 4,
                            TemplateId = 1L,
                            UpdatedAt = new DateTime(2025, 12, 26, 3, 29, 36, 249, DateTimeKind.Local).AddTicks(135)
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2025, 12, 26, 3, 29, 36, 249, DateTimeKind.Local).AddTicks(136),
                            Description = "合格",
                            IsDeleted = false,
                            LevelCode = "是",
                            Ratio = 1.0m,
                            Sort = 1,
                            TemplateId = 2L,
                            UpdatedAt = new DateTime(2025, 12, 26, 3, 29, 36, 249, DateTimeKind.Local).AddTicks(137)
                        },
                        new
                        {
                            Id = 6L,
                            CreatedAt = new DateTime(2025, 12, 26, 3, 29, 36, 249, DateTimeKind.Local).AddTicks(139),
                            Description = "不合格",
                            IsDeleted = false,
                            LevelCode = "否",
                            Ratio = 0.0m,
                            Sort = 2,
                            TemplateId = 2L,
                            UpdatedAt = new DateTime(2025, 12, 26, 3, 29, 36, 249, DateTimeKind.Local).AddTicks(140)
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.SpeEvalNode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Depth")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("MaxScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Path")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<long?>("ScoringTemplateId")
                        .HasColumnType("bigint");

                    b.Property<long>("TreeId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("spe_eval_nodes");

                    b.HasData(
                        new
                        {
                            Id = 10000L,
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 251, DateTimeKind.Utc).AddTicks(4183),
                            Depth = 0,
                            IsDeleted = false,
                            MaxScore = 100m,
                            Name = "2025特教学校办学质量评价",
                            OrderIndex = 0,
                            Path = "0",
                            TreeId = 202501L,
                            Type = 0,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 251, DateTimeKind.Utc).AddTicks(4185)
                        },
                        new
                        {
                            Id = 10001L,
                            Code = "1",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 251, DateTimeKind.Utc).AddTicks(5277),
                            Depth = 1,
                            IsDeleted = false,
                            MaxScore = 20m,
                            Name = "办学方向",
                            OrderIndex = 0,
                            ParentId = 10000L,
                            Path = "0,10000",
                            TreeId = 202501L,
                            Type = 1,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 251, DateTimeKind.Utc).AddTicks(5277)
                        },
                        new
                        {
                            Id = 10002L,
                            Code = "1.1",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 251, DateTimeKind.Utc).AddTicks(8048),
                            Depth = 2,
                            IsDeleted = false,
                            MaxScore = 10m,
                            Name = "党的领导",
                            OrderIndex = 0,
                            ParentId = 10001L,
                            Path = "0,10000,10001",
                            TreeId = 202501L,
                            Type = 2,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 251, DateTimeKind.Utc).AddTicks(8049)
                        },
                        new
                        {
                            Id = 10003L,
                            Code = "1.1.1",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 251, DateTimeKind.Utc).AddTicks(8065),
                            Depth = 3,
                            IsDeleted = false,
                            MaxScore = 10m,
                            Name = "党建工作常态化",
                            OrderIndex = 0,
                            ParentId = 10002L,
                            Path = "0,10000,10001,10002",
                            ScoringTemplateId = 2L,
                            TreeId = 202501L,
                            Type = 4,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 251, DateTimeKind.Utc).AddTicks(8065)
                        },
                        new
                        {
                            Id = 10004L,
                            Code = "2",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 251, DateTimeKind.Utc).AddTicks(8233),
                            Depth = 1,
                            IsDeleted = false,
                            MaxScore = 40m,
                            Name = "教育教学",
                            OrderIndex = 0,
                            ParentId = 10000L,
                            Path = "0,10000",
                            TreeId = 202501L,
                            Type = 1,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 251, DateTimeKind.Utc).AddTicks(8233)
                        },
                        new
                        {
                            Id = 10005L,
                            Code = "2.1",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 251, DateTimeKind.Utc).AddTicks(8240),
                            Depth = 2,
                            IsDeleted = false,
                            MaxScore = 20m,
                            Name = "个别化教育",
                            OrderIndex = 0,
                            ParentId = 10004L,
                            Path = "0,10000,10004",
                            TreeId = 202501L,
                            Type = 2,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 251, DateTimeKind.Utc).AddTicks(8241)
                        },
                        new
                        {
                            Id = 10006L,
                            Code = "2.1.1",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 251, DateTimeKind.Utc).AddTicks(8244),
                            Depth = 3,
                            IsDeleted = false,
                            MaxScore = 10m,
                            Name = "IEP制定规范",
                            OrderIndex = 0,
                            ParentId = 10005L,
                            Path = "0,10000,10004,10005",
                            TreeId = 202501L,
                            Type = 3,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 251, DateTimeKind.Utc).AddTicks(8244)
                        },
                        new
                        {
                            Id = 10007L,
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 251, DateTimeKind.Utc).AddTicks(8247),
                            Depth = 4,
                            IsDeleted = false,
                            Name = "查阅10份学生档案，检查IEP要素是否齐全。",
                            OrderIndex = 0,
                            ParentId = 10006L,
                            Path = "0,10000,10004,10005,10006",
                            TreeId = 202501L,
                            Type = 5,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 251, DateTimeKind.Utc).AddTicks(8247)
                        },
                        new
                        {
                            Id = 10008L,
                            Code = "2.1.2",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 251, DateTimeKind.Utc).AddTicks(8250),
                            Depth = 3,
                            IsDeleted = false,
                            MaxScore = 10m,
                            Name = "IEP实施效果",
                            OrderIndex = 0,
                            ParentId = 10005L,
                            Path = "0,10000,10004,10005",
                            ScoringTemplateId = 1L,
                            TreeId = 202501L,
                            Type = 4,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 251, DateTimeKind.Utc).AddTicks(8250)
                        },
                        new
                        {
                            Id = 10009L,
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 251, DateTimeKind.Utc).AddTicks(8254),
                            Depth = 0,
                            IsDeleted = false,
                            MaxScore = 100m,
                            Name = "2024河北省特教质量监测",
                            OrderIndex = 0,
                            Path = "0",
                            TreeId = 202401L,
                            Type = 0,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 251, DateTimeKind.Utc).AddTicks(8255)
                        },
                        new
                        {
                            Id = 10010L,
                            Code = "A",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 251, DateTimeKind.Utc).AddTicks(8256),
                            Depth = 1,
                            IsDeleted = false,
                            MaxScore = 50m,
                            Name = "校园安全",
                            OrderIndex = 0,
                            ParentId = 10009L,
                            Path = "0,10009",
                            TreeId = 202401L,
                            Type = 1,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 251, DateTimeKind.Utc).AddTicks(8256)
                        },
                        new
                        {
                            Id = 10011L,
                            Code = "A-1",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 251, DateTimeKind.Utc).AddTicks(8259),
                            Depth = 2,
                            IsDeleted = false,
                            MaxScore = 50m,
                            Name = "无障碍设施",
                            OrderIndex = 0,
                            ParentId = 10010L,
                            Path = "0,10009,10010",
                            ScoringTemplateId = 1L,
                            TreeId = 202401L,
                            Type = 4,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 251, DateTimeKind.Utc).AddTicks(8259)
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.SysRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("remark")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("sys_role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ADMIN",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 264, DateTimeKind.Utc).AddTicks(5905),
                            IsDeleted = false,
                            Name = "管理员",
                            Sort = 1,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 264, DateTimeKind.Utc).AddTicks(5992),
                            remark = "系统超级管理员"
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.SysUsers", b =>
                {
                    b.Property<string>("IDNumber")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OrgId")
                        .HasColumnType("longtext");

                    b.Property<int>("OrgType")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<string>("RealName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserName")
                        .HasColumnType("varchar(255)");

                    b.HasKey("IDNumber");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("sys_users");

                    b.HasData(
                        new
                        {
                            IDNumber = "110000198001010001",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 270, DateTimeKind.Utc).AddTicks(7666),
                            IsDeleted = false,
                            OrgId = "110000_EDU",
                            OrgType = 2,
                            Password = "7C4A8D09CA3762AF61E59520943DC26494F8941B",
                            Phone = "13800000000",
                            RealName = "超级管理员",
                            Role = 0,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 270, DateTimeKind.Utc).AddTicks(7669),
                            UserName = "admin"
                        },
                        new
                        {
                            IDNumber = "110105198501010001",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 270, DateTimeKind.Utc).AddTicks(8484),
                            IsDeleted = false,
                            OrgId = "110105_EDU",
                            OrgType = 2,
                            Password = "7C4A8D09CA3762AF61E59520943DC26494F8941B",
                            Phone = "13800000001",
                            RealName = "朝阳区管理员",
                            Role = 0,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 270, DateTimeKind.Utc).AddTicks(8485),
                            UserName = "admin_cy"
                        },
                        new
                        {
                            IDNumber = "130100198502020001",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 270, DateTimeKind.Utc).AddTicks(8487),
                            IsDeleted = false,
                            OrgId = "130100_EDU",
                            OrgType = 2,
                            Password = "7C4A8D09CA3762AF61E59520943DC26494F8941B",
                            Phone = "13800000002",
                            RealName = "石家庄管理员",
                            Role = 0,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 270, DateTimeKind.Utc).AddTicks(8487),
                            UserName = "admin_sjz"
                        },
                        new
                        {
                            IDNumber = "110105199001010001",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 270, DateTimeKind.Utc).AddTicks(8489),
                            IsDeleted = false,
                            OrgId = "110105_SPE_01",
                            OrgType = 0,
                            Password = "7C4A8D09CA3762AF61E59520943DC26494F8941B",
                            Phone = "13900000001",
                            RealName = "安华学校校长",
                            Role = 2,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 270, DateTimeKind.Utc).AddTicks(8489),
                            UserName = "sch_cy_spe"
                        },
                        new
                        {
                            IDNumber = "130100199002020001",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 270, DateTimeKind.Utc).AddTicks(8490),
                            IsDeleted = false,
                            OrgId = "130100_SPE_01",
                            OrgType = 0,
                            Password = "7C4A8D09CA3762AF61E59520943DC26494F8941B",
                            Phone = "13900000002",
                            RealName = "石特校长",
                            Role = 2,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 270, DateTimeKind.Utc).AddTicks(8490),
                            UserName = "sch_sjz_spe"
                        },
                        new
                        {
                            IDNumber = "110108199003030001",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 270, DateTimeKind.Utc).AddTicks(8497),
                            IsDeleted = false,
                            OrgId = "110108_INC_01",
                            OrgType = 1,
                            Password = "7C4A8D09CA3762AF61E59520943DC26494F8941B",
                            Phone = "13900000003",
                            RealName = "中关村校长",
                            Role = 2,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 270, DateTimeKind.Utc).AddTicks(8497),
                            UserName = "sch_hd_inc"
                        },
                        new
                        {
                            IDNumber = "110000197001010001",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 270, DateTimeKind.Utc).AddTicks(8498),
                            IsDeleted = false,
                            OrgId = "110000_OTH_01",
                            OrgType = 3,
                            Password = "7C4A8D09CA3762AF61E59520943DC26494F8941B",
                            Phone = "13600000001",
                            RealName = "特教专家",
                            Role = 1,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 270, DateTimeKind.Utc).AddTicks(8499),
                            UserName = "expert_01"
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.TaskEvidences", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FileUrls")
                        .HasColumnType("json");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("NodeId")
                        .HasColumnType("bigint");

                    b.Property<string>("RejectReason")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("TaskId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("task_evidences");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Content = "自评报告内容...",
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 259, DateTimeKind.Utc).AddTicks(2910),
                            FileUrls = "[\"http://file/a.pdf\"]",
                            IsDeleted = false,
                            NodeId = 3L,
                            Status = 0,
                            TaskId = 1L,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 259, DateTimeKind.Utc).AddTicks(2266)
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.Tasks", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("BatchId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("FinalScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TargetId")
                        .HasColumnType("longtext");

                    b.Property<int>("TargetType")
                        .HasColumnType("int");

                    b.Property<long>("TreeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("tasks");

                    b.HasData(
                        new
                        {
                            Id = 30000L,
                            BatchId = 10000L,
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 275, DateTimeKind.Utc).AddTicks(1652),
                            IsDeleted = false,
                            Status = 2,
                            TargetId = "110105_SPE_01",
                            TargetType = 0,
                            TreeId = 202501L,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 275, DateTimeKind.Utc).AddTicks(1653)
                        },
                        new
                        {
                            Id = 30001L,
                            BatchId = 10000L,
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 275, DateTimeKind.Utc).AddTicks(2272),
                            IsDeleted = false,
                            Status = 3,
                            SubmittedAt = new DateTime(2025, 12, 24, 19, 29, 36, 275, DateTimeKind.Utc).AddTicks(2274),
                            TargetId = "130100_SPE_01",
                            TargetType = 0,
                            TreeId = 202501L,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 275, DateTimeKind.Utc).AddTicks(2273)
                        },
                        new
                        {
                            Id = 30002L,
                            BatchId = 10001L,
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 275, DateTimeKind.Utc).AddTicks(2464),
                            IsDeleted = false,
                            Status = 0,
                            TargetId = "110108_INC_01",
                            TargetType = 1,
                            TreeId = 202502L,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 275, DateTimeKind.Utc).AddTicks(2464)
                        },
                        new
                        {
                            Id = 30003L,
                            BatchId = 10002L,
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 275, DateTimeKind.Utc).AddTicks(2466),
                            IsDeleted = false,
                            Status = 4,
                            SubmittedAt = new DateTime(2025, 12, 23, 19, 29, 36, 275, DateTimeKind.Utc).AddTicks(2467),
                            TargetId = "110105_EDU",
                            TargetType = 2,
                            TreeId = 202503L,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 275, DateTimeKind.Utc).AddTicks(2466)
                        },
                        new
                        {
                            Id = 30004L,
                            BatchId = 10003L,
                            CreatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 275, DateTimeKind.Utc).AddTicks(2468),
                            FinalScore = 88.5m,
                            IsDeleted = false,
                            Status = 6,
                            SubmittedAt = new DateTime(2024, 12, 25, 19, 29, 36, 275, DateTimeKind.Utc).AddTicks(2469),
                            TargetId = "130400_SPE_01",
                            TargetType = 0,
                            TreeId = 202401L,
                            UpdatedAt = new DateTime(2025, 12, 25, 19, 29, 36, 275, DateTimeKind.Utc).AddTicks(2468)
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.ScoringModelItem", b =>
                {
                    b.HasOne("Tsjy.Core.Entities.ScoringModel", null)
                        .WithMany("Items")
                        .HasForeignKey("ScoringModelId");
                });

            modelBuilder.Entity("Tsjy.Core.Entities.ScoringModel", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
