// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tsjy.EntityFramework.Core;

#nullable disable

namespace Tsjy.Database.Migrations.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    [Migration("20251208125029_v1.0.0")]
    partial class v100
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Tsjy.Core.Entities.AiPreEvaluation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("AnalysisReport")
                        .HasColumnType("longtext");

                    b.Property<long>("AssignmentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("EvidenceId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("NodeId")
                        .HasColumnType("bigint");

                    b.Property<string>("RiskLevel")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("SuggestedScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("ai_pre_evaluations");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AnalysisReport = "AI分析通过",
                            AssignmentId = 1L,
                            CreatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 693, DateTimeKind.Utc).AddTicks(2574),
                            EvidenceId = 1L,
                            IsDeleted = false,
                            NodeId = 3L,
                            RiskLevel = "low",
                            SuggestedScore = 4.5m,
                            UpdatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 693, DateTimeKind.Utc).AddTicks(2575),
                            UserId = 1L
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.Assignment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("BatchId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DueAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("FinalScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("TargetId")
                        .HasColumnType("bigint");

                    b.Property<int>("TargetType")
                        .HasColumnType("int");

                    b.Property<long>("TreeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("assignments");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BatchId = 1L,
                            CreatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 715, DateTimeKind.Utc).AddTicks(8193),
                            DueAt = new DateTime(2025, 12, 15, 12, 50, 28, 715, DateTimeKind.Utc).AddTicks(8114),
                            IsDeleted = false,
                            StartAt = new DateTime(2025, 12, 8, 12, 50, 28, 715, DateTimeKind.Utc).AddTicks(7994),
                            Status = 2,
                            TargetId = 1L,
                            TargetType = 0,
                            TreeId = 202501L,
                            UpdatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 715, DateTimeKind.Utc).AddTicks(7479)
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.AssignmentEvidence", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("AssignmentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FileUrls")
                        .HasColumnType("json");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("NodeId")
                        .HasColumnType("bigint");

                    b.Property<string>("RejectReason")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("assignment_evidences");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AssignmentId = 1L,
                            Content = "自评报告内容...",
                            CreatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 691, DateTimeKind.Utc).AddTicks(9458),
                            FileUrls = "[\"http://file/a.pdf\"]",
                            IsDeleted = false,
                            NodeId = 3L,
                            Status = 0,
                            UpdatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 691, DateTimeKind.Utc).AddTicks(8903)
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.BatchTarget", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("BatchId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("OrgId")
                        .HasColumnType("bigint");

                    b.Property<int>("OrgType")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("batch_targets");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BatchId = 1L,
                            CreatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 713, DateTimeKind.Utc).AddTicks(2276),
                            IsDeleted = false,
                            OrgId = 1L,
                            OrgType = 0,
                            UpdatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 713, DateTimeKind.Utc).AddTicks(1911)
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.DistributionBatch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("TreeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("distribution_batches");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 712, DateTimeKind.Utc).AddTicks(2422),
                            IsDeleted = false,
                            Name = "2025年度第一次普查",
                            Status = 1,
                            TreeId = 202501L,
                            UpdatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 712, DateTimeKind.Utc).AddTicks(1926)
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.EduEvalNode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Depth")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("MaxScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Path")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<long?>("ScoringModelId")
                        .HasColumnType("bigint");

                    b.Property<long>("TreeId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("edu_eval_nodes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 688, DateTimeKind.Utc).AddTicks(1492),
                            Depth = 0,
                            IsDeleted = false,
                            MaxScore = 100m,
                            Name = "河北省特教评价2025",
                            OrderIndex = 0,
                            Path = "0",
                            TreeId = 202501L,
                            Type = 0,
                            UpdatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 688, DateTimeKind.Utc).AddTicks(1494)
                        },
                        new
                        {
                            Id = 2L,
                            Code = "1",
                            CreatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 688, DateTimeKind.Utc).AddTicks(2432),
                            Depth = 1,
                            IsDeleted = false,
                            MaxScore = 20m,
                            Name = "办学方向",
                            OrderIndex = 0,
                            ParentId = 1L,
                            Path = "0,1",
                            TreeId = 202501L,
                            Type = 1,
                            UpdatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 688, DateTimeKind.Utc).AddTicks(2432)
                        },
                        new
                        {
                            Id = 3L,
                            Code = "1.1",
                            CreatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 688, DateTimeKind.Utc).AddTicks(2524),
                            Depth = 2,
                            IsDeleted = false,
                            MaxScore = 5m,
                            Name = "坚持办学方向",
                            OrderIndex = 0,
                            ParentId = 2L,
                            Path = "0,1,2",
                            ScoringModelId = 1L,
                            TreeId = 202501L,
                            Type = 4,
                            UpdatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 688, DateTimeKind.Utc).AddTicks(2525)
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.EducationBureau", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("Code")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("IncSchoolsNum")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Level")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<long>("RegionId")
                        .HasColumnType("bigint");

                    b.Property<long>("SpeSchoolsNum")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("education_bureaus");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Address = "市局地址",
                            Code = "B130100",
                            CreatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 532, DateTimeKind.Utc).AddTicks(3587),
                            IncSchoolsNum = 10L,
                            IsDeleted = false,
                            Level = "city",
                            Name = "石家庄市教育局",
                            Phone = 12345678,
                            RegionId = 2L,
                            SpeSchoolsNum = 1L,
                            UpdatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 532, DateTimeKind.Utc).AddTicks(1954)
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.ExpertReview", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("AssignmentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("FinalScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("NodeId")
                        .HasColumnType("bigint");

                    b.Property<long>("ReviewerId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("ScoreRatio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StandardScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("expert_reviews");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AssignmentId = 1L,
                            CreatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 696, DateTimeKind.Utc).AddTicks(9042),
                            FinalScore = 4.0m,
                            IsDeleted = false,
                            NodeId = 3L,
                            ReviewerId = 100L,
                            ScoreRatio = 0.8m,
                            StandardScore = 5m,
                            UpdatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 696, DateTimeKind.Utc).AddTicks(8333)
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.IncEvalNode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Depth")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("MaxScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Path")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<long?>("ScoringModelId")
                        .HasColumnType("bigint");

                    b.Property<long>("TreeId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("inc_eval_nodes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 686, DateTimeKind.Utc).AddTicks(5528),
                            Depth = 0,
                            IsDeleted = false,
                            MaxScore = 100m,
                            Name = "河北省特教评价2025",
                            OrderIndex = 0,
                            Path = "0",
                            TreeId = 202501L,
                            Type = 0,
                            UpdatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 686, DateTimeKind.Utc).AddTicks(5531)
                        },
                        new
                        {
                            Id = 2L,
                            Code = "1",
                            CreatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 686, DateTimeKind.Utc).AddTicks(6465),
                            Depth = 1,
                            IsDeleted = false,
                            MaxScore = 20m,
                            Name = "办学方向",
                            OrderIndex = 0,
                            ParentId = 1L,
                            Path = "0,1",
                            TreeId = 202501L,
                            Type = 1,
                            UpdatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 686, DateTimeKind.Utc).AddTicks(6465)
                        },
                        new
                        {
                            Id = 3L,
                            Code = "1.1",
                            CreatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 686, DateTimeKind.Utc).AddTicks(6551),
                            Depth = 2,
                            IsDeleted = false,
                            MaxScore = 5m,
                            Name = "坚持办学方向",
                            OrderIndex = 0,
                            ParentId = 2L,
                            Path = "0,1,2",
                            ScoringModelId = 1L,
                            TreeId = 202501L,
                            Type = 4,
                            UpdatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 686, DateTimeKind.Utc).AddTicks(6552)
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.InclusiveSchool", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("Code")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<long>("RegionId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("inclusive_schools");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Address = "长安区地址",
                            Code = "I1301021",
                            CreatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 531, DateTimeKind.Utc).AddTicks(916),
                            IsDeleted = false,
                            Name = "石家庄市长安区第一小学(融合校)",
                            Phone = 66666666,
                            RegionId = 3L,
                            UpdatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 531, DateTimeKind.Utc).AddTicks(329)
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.InspectionLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("EvidenceFiles")
                        .HasColumnType("json");

                    b.Property<string>("Findings")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("NodeId")
                        .HasColumnType("bigint");

                    b.Property<long>("ScheduleId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("inspection_logs");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 702, DateTimeKind.Utc).AddTicks(3205),
                            CreatedBy = 100L,
                            EvidenceFiles = "[\"photo1.jpg\"]",
                            Findings = "现场查看符合要求",
                            IsDeleted = false,
                            NodeId = 3L,
                            ScheduleId = 1L,
                            UpdatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 702, DateTimeKind.Utc).AddTicks(3206)
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.InspectionSchedule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("AssignmentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("TeamId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("VisitEndAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("VisitStartAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("inspection_schedules");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AssignmentId = 1L,
                            CreatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 701, DateTimeKind.Utc).AddTicks(122),
                            IsDeleted = false,
                            Status = 0,
                            TeamId = 1L,
                            UpdatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 701, DateTimeKind.Utc).AddTicks(124),
                            VisitEndAt = new DateTime(2025, 12, 10, 12, 50, 28, 701, DateTimeKind.Utc).AddTicks(627),
                            VisitStartAt = new DateTime(2025, 12, 9, 12, 50, 28, 701, DateTimeKind.Utc).AddTicks(430)
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.InspectionTeam", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("BatchId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("inspection_teams");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BatchId = 1L,
                            CreatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 697, DateTimeKind.Utc).AddTicks(8472),
                            IsDeleted = false,
                            Name = "第一视导组",
                            UpdatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 697, DateTimeKind.Utc).AddTicks(8134)
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.InspectionTeamMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("TeamId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("inspection_team_members");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 698, DateTimeKind.Utc).AddTicks(9359),
                            IsDeleted = false,
                            TeamId = 1L,
                            UpdatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 698, DateTimeKind.Utc).AddTicks(9027),
                            UserId = 100L
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.Region", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("regions");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "130000",
                            CreatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 527, DateTimeKind.Utc).AddTicks(4643),
                            IsDeleted = false,
                            Level = 0,
                            Name = "河北省",
                            UpdatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 527, DateTimeKind.Utc).AddTicks(4211)
                        },
                        new
                        {
                            Id = 2L,
                            Code = "130100",
                            CreatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 527, DateTimeKind.Utc).AddTicks(4747),
                            IsDeleted = false,
                            Level = 1,
                            Name = "石家庄市",
                            UpdatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 527, DateTimeKind.Utc).AddTicks(4746)
                        },
                        new
                        {
                            Id = 3L,
                            Code = "130102",
                            CreatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 527, DateTimeKind.Utc).AddTicks(4749),
                            IsDeleted = false,
                            Level = 2,
                            Name = "长安区",
                            UpdatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 527, DateTimeKind.Utc).AddTicks(4748)
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.ReviewAllocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("AssignmentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("ExpertId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("NodeId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("review_allocations");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AssignedAt = new DateTime(2025, 12, 8, 12, 50, 28, 695, DateTimeKind.Utc).AddTicks(6933),
                            AssignmentId = 1L,
                            CreatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 695, DateTimeKind.Utc).AddTicks(6479),
                            ExpertId = 100L,
                            IsDeleted = false,
                            NodeId = 3L,
                            Status = 0,
                            UpdatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 695, DateTimeKind.Utc).AddTicks(6479)
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.ScoringModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("scoring_models");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "标准四级制 (A/B/C/D)",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "符合性判断 (是/否)",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.ScoringModelItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LevelCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<long>("ModelId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Ratio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("scoring_model_items");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "优秀/落实到位",
                            IsDeleted = false,
                            LevelCode = "A",
                            ModelId = 1L,
                            Ratio = 1.0m,
                            Sort = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "良好/基本落实",
                            IsDeleted = false,
                            LevelCode = "B",
                            ModelId = 1L,
                            Ratio = 0.8m,
                            Sort = 1,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "合格/部分落实",
                            IsDeleted = false,
                            LevelCode = "C",
                            ModelId = 1L,
                            Ratio = 0.6m,
                            Sort = 2,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "不合格/未落实",
                            IsDeleted = false,
                            LevelCode = "D",
                            ModelId = 1L,
                            Ratio = 0.0m,
                            Sort = 3,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "符合/是",
                            IsDeleted = false,
                            LevelCode = "A",
                            ModelId = 2L,
                            Ratio = 1.0m,
                            Sort = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "不符合/否",
                            IsDeleted = false,
                            LevelCode = "B",
                            ModelId = 2L,
                            Ratio = 0.0m,
                            Sort = 1,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.SpeEvalNode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Depth")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("MaxScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Path")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<long?>("ScoringModelId")
                        .HasColumnType("bigint");

                    b.Property<long>("TreeId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("spe_eval_nodes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 684, DateTimeKind.Utc).AddTicks(9606),
                            Depth = 0,
                            IsDeleted = false,
                            MaxScore = 100m,
                            Name = "河北省特教评价2025",
                            OrderIndex = 0,
                            Path = "0",
                            TreeId = 202501L,
                            Type = 0,
                            UpdatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 684, DateTimeKind.Utc).AddTicks(9608)
                        },
                        new
                        {
                            Id = 2L,
                            Code = "1",
                            CreatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 685, DateTimeKind.Utc).AddTicks(700),
                            Depth = 1,
                            IsDeleted = false,
                            MaxScore = 20m,
                            Name = "办学方向",
                            OrderIndex = 0,
                            ParentId = 1L,
                            Path = "0,1",
                            TreeId = 202501L,
                            Type = 1,
                            UpdatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 685, DateTimeKind.Utc).AddTicks(700)
                        },
                        new
                        {
                            Id = 3L,
                            Code = "1.1",
                            CreatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 685, DateTimeKind.Utc).AddTicks(795),
                            Depth = 2,
                            IsDeleted = false,
                            MaxScore = 5m,
                            Name = "坚持办学方向",
                            OrderIndex = 0,
                            ParentId = 2L,
                            Path = "0,1,2",
                            ScoringModelId = 1L,
                            TreeId = 202501L,
                            Type = 4,
                            UpdatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 685, DateTimeKind.Utc).AddTicks(795)
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.SpecialSchool", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("Code")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<long>("RegionId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("special_schools");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Address = "学校地址",
                            Code = "S1301001",
                            CreatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 529, DateTimeKind.Utc).AddTicks(9260),
                            IsDeleted = false,
                            Name = "石家庄市特殊教育学校",
                            Phone = 87654321,
                            RegionId = 2L,
                            Status = 1,
                            UpdatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 529, DateTimeKind.Utc).AddTicks(8614)
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.SysRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("remark")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("sys_role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ADMIN",
                            CreatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 703, DateTimeKind.Utc).AddTicks(5962),
                            IsDeleted = false,
                            Name = "管理员",
                            Sort = 1,
                            UpdatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 703, DateTimeKind.Utc).AddTicks(6049),
                            remark = "系统超级管理员"
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.SysUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Account")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("OrgId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("User_type")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("sys_user");
                });

            modelBuilder.Entity("Tsjy.Core.Entities.SysUsers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("OrgId")
                        .HasColumnType("int");

                    b.Property<int>("OrgType")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<string>("RealName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserName")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("sys_users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 710, DateTimeKind.Utc).AddTicks(4577),
                            IsDeleted = false,
                            OrgId = 1,
                            OrgType = 2,
                            Password = "7C4A8D09CA3762AF61E59520943DC26494F8941B",
                            Phone = "13800000000",
                            RealName = "超级管理员",
                            Role = 0,
                            UpdatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 710, DateTimeKind.Utc).AddTicks(4697),
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 100,
                            CreatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 710, DateTimeKind.Utc).AddTicks(4922),
                            IsDeleted = false,
                            OrgId = 1,
                            OrgType = 2,
                            Password = "7C4A8D09CA3762AF61E59520943DC26494F8941B",
                            Phone = "13800000000",
                            RealName = "超级管理员",
                            Role = 0,
                            UpdatedAt = new DateTime(2025, 12, 8, 12, 50, 28, 710, DateTimeKind.Utc).AddTicks(4923),
                            UserName = "100"
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.ScoringModelItem", b =>
                {
                    b.HasOne("Tsjy.Core.Entities.ScoringModel", null)
                        .WithMany("Items")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tsjy.Core.Entities.ScoringModel", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
