// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tsjy.EntityFramework.Core;

#nullable disable

namespace Tsjy.Database.Migrations.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    partial class DefaultDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Tsjy.Core.Entities.AiPreEvaluation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("AnalysisReport")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("EvidenceId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("NodeId")
                        .HasColumnType("bigint");

                    b.Property<string>("RiskLevel")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("SuggestedScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("TaskId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("ai_pre_evaluations");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AnalysisReport = "AI分析通过",
                            CreatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 492, DateTimeKind.Utc).AddTicks(5547),
                            EvidenceId = 1L,
                            IsDeleted = false,
                            NodeId = 3L,
                            RiskLevel = "low",
                            SuggestedScore = 4.5m,
                            TaskId = 1L,
                            UpdatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 492, DateTimeKind.Utc).AddTicks(5551),
                            UserId = 1L
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.AssignmentEvidence", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FileUrls")
                        .HasColumnType("json");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("NodeId")
                        .HasColumnType("bigint");

                    b.Property<string>("RejectReason")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("TaskId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("task_evidences");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Content = "自评报告内容...",
                            CreatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 491, DateTimeKind.Utc).AddTicks(4644),
                            FileUrls = "[\"http://file/a.pdf\"]",
                            IsDeleted = false,
                            NodeId = 3L,
                            Status = 0,
                            TaskId = 1L,
                            UpdatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 491, DateTimeKind.Utc).AddTicks(4077)
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.BatchTarget", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("BatchId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("OrgId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("batch_targets");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BatchId = 1L,
                            CreatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 514, DateTimeKind.Utc).AddTicks(6114),
                            IsDeleted = false,
                            OrgId = 1L,
                            UpdatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 514, DateTimeKind.Utc).AddTicks(5828)
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.Departments", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("IncSchoolsNum")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("OrgType")
                        .HasColumnType("int");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<string>("RegionCode")
                        .HasColumnType("longtext");

                    b.Property<long>("SpeSchoolsNum")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Code");

                    b.ToTable("departments");

                    b.HasData(
                        new
                        {
                            Code = "330100_EDU",
                            Address = "杭州市某某路1号",
                            CreatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 441, DateTimeKind.Utc).AddTicks(715),
                            IncSchoolsNum = 120L,
                            IsDeleted = false,
                            Level = 1,
                            Name = "杭州市教育局",
                            OrgType = 2,
                            Phone = 88888888,
                            RegionCode = "330100",
                            SpeSchoolsNum = 8L,
                            UpdatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 440, DateTimeKind.Utc).AddTicks(8855)
                        },
                        new
                        {
                            Code = "330106_EDU",
                            Address = "西湖区某某路2号",
                            CreatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 441, DateTimeKind.Utc).AddTicks(843),
                            IncSchoolsNum = 45L,
                            IsDeleted = false,
                            Level = 2,
                            Name = "西湖区教育局",
                            OrgType = 2,
                            Phone = 66666666,
                            RegionCode = "330106",
                            SpeSchoolsNum = 2L,
                            UpdatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 441, DateTimeKind.Utc).AddTicks(840)
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.DistributionBatch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("TreeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("distribution_batches");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 513, DateTimeKind.Utc).AddTicks(6728),
                            IsDeleted = false,
                            Name = "2025年度第一次普查",
                            Status = 1,
                            TreeId = 202501L,
                            UpdatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 513, DateTimeKind.Utc).AddTicks(6315)
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.EduEvalNode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Depth")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("MaxScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Path")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<long?>("ScoringTemplateId")
                        .HasColumnType("bigint");

                    b.Property<long>("TreeId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("edu_eval_nodes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 487, DateTimeKind.Utc).AddTicks(5027),
                            Depth = 0,
                            IsDeleted = false,
                            MaxScore = 100m,
                            Name = "河北省特教评价2025",
                            OrderIndex = 0,
                            Path = "0",
                            TreeId = 202501L,
                            Type = 0,
                            UpdatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 487, DateTimeKind.Utc).AddTicks(5032)
                        },
                        new
                        {
                            Id = 2L,
                            Code = "1",
                            CreatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 487, DateTimeKind.Utc).AddTicks(6054),
                            Depth = 1,
                            IsDeleted = false,
                            MaxScore = 20m,
                            Name = "办学方向",
                            OrderIndex = 0,
                            ParentId = 1L,
                            Path = "0,1",
                            TreeId = 202501L,
                            Type = 1,
                            UpdatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 487, DateTimeKind.Utc).AddTicks(6054)
                        },
                        new
                        {
                            Id = 3L,
                            Code = "1.1",
                            CreatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 487, DateTimeKind.Utc).AddTicks(6140),
                            Depth = 2,
                            IsDeleted = false,
                            MaxScore = 5m,
                            Name = "坚持办学方向",
                            OrderIndex = 0,
                            ParentId = 2L,
                            Path = "0,1,2",
                            ScoringTemplateId = 1L,
                            TreeId = 202501L,
                            Type = 4,
                            UpdatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 487, DateTimeKind.Utc).AddTicks(6140)
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.ExpertReview", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("FinalScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("NodeId")
                        .HasColumnType("bigint");

                    b.Property<long>("ReviewerId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("ScoreRatio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StandardScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("TaskId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("expert_reviews");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 496, DateTimeKind.Utc).AddTicks(5747),
                            FinalScore = 4.0m,
                            IsDeleted = false,
                            NodeId = 3L,
                            ReviewerId = 100L,
                            ScoreRatio = 0.8m,
                            StandardScore = 5m,
                            TaskId = 1L,
                            UpdatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 496, DateTimeKind.Utc).AddTicks(5085)
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.IncEvalNode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Depth")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("MaxScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Path")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<long?>("ScoringTemplateId")
                        .HasColumnType("bigint");

                    b.Property<long>("TreeId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("inc_eval_nodes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 485, DateTimeKind.Utc).AddTicks(7515),
                            Depth = 0,
                            IsDeleted = false,
                            MaxScore = 100m,
                            Name = "河北省特教评价2025",
                            OrderIndex = 0,
                            Path = "0",
                            TreeId = 202501L,
                            Type = 0,
                            UpdatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 485, DateTimeKind.Utc).AddTicks(7517)
                        },
                        new
                        {
                            Id = 2L,
                            Code = "1",
                            CreatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 485, DateTimeKind.Utc).AddTicks(8373),
                            Depth = 1,
                            IsDeleted = false,
                            MaxScore = 20m,
                            Name = "办学方向",
                            OrderIndex = 0,
                            ParentId = 1L,
                            Path = "0,1",
                            TreeId = 202501L,
                            Type = 1,
                            UpdatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 485, DateTimeKind.Utc).AddTicks(8374)
                        },
                        new
                        {
                            Id = 3L,
                            Code = "1.1",
                            CreatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 485, DateTimeKind.Utc).AddTicks(8455),
                            Depth = 2,
                            IsDeleted = false,
                            MaxScore = 5m,
                            Name = "坚持办学方向",
                            OrderIndex = 0,
                            ParentId = 2L,
                            Path = "0,1,2",
                            ScoringTemplateId = 1L,
                            TreeId = 202501L,
                            Type = 4,
                            UpdatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 485, DateTimeKind.Utc).AddTicks(8455)
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.InspectionLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("EvidenceFiles")
                        .HasColumnType("json");

                    b.Property<string>("Findings")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("NodeId")
                        .HasColumnType("bigint");

                    b.Property<long>("ScheduleId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("inspection_logs");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 502, DateTimeKind.Utc).AddTicks(726),
                            CreatedBy = 100L,
                            EvidenceFiles = "[\"photo1.jpg\"]",
                            Findings = "现场查看符合要求",
                            IsDeleted = false,
                            NodeId = 3L,
                            ScheduleId = 1L,
                            UpdatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 502, DateTimeKind.Utc).AddTicks(727)
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.InspectionSchedule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("AssignmentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("TeamId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("VisitEndAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("VisitStartAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("inspection_schedules");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AssignmentId = 1L,
                            CreatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 500, DateTimeKind.Utc).AddTicks(7500),
                            IsDeleted = false,
                            Status = 0,
                            TeamId = 1L,
                            UpdatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 500, DateTimeKind.Utc).AddTicks(7502),
                            VisitEndAt = new DateTime(2025, 12, 12, 7, 52, 15, 500, DateTimeKind.Utc).AddTicks(7972),
                            VisitStartAt = new DateTime(2025, 12, 11, 7, 52, 15, 500, DateTimeKind.Utc).AddTicks(7809)
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.InspectionTeam", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("BatchId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("inspection_teams");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BatchId = 1L,
                            CreatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 497, DateTimeKind.Utc).AddTicks(7358),
                            IsDeleted = false,
                            Name = "第一视导组",
                            UpdatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 497, DateTimeKind.Utc).AddTicks(7029)
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.InspectionTeamMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("TeamId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("inspection_team_members");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 498, DateTimeKind.Utc).AddTicks(8335),
                            IsDeleted = false,
                            TeamId = 1L,
                            UpdatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 498, DateTimeKind.Utc).AddTicks(8019),
                            UserId = 100L
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.Region", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ParentCode")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Code");

                    b.ToTable("regions");

                    b.HasData(
                        new
                        {
                            Code = "330000",
                            CreatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 437, DateTimeKind.Utc).AddTicks(1204),
                            IsDeleted = false,
                            Level = 0,
                            Name = "浙江省",
                            UpdatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 437, DateTimeKind.Utc).AddTicks(764)
                        },
                        new
                        {
                            Code = "330100",
                            CreatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 437, DateTimeKind.Utc).AddTicks(1303),
                            IsDeleted = false,
                            Level = 1,
                            Name = "杭州市",
                            ParentCode = "330000",
                            UpdatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 437, DateTimeKind.Utc).AddTicks(1301)
                        },
                        new
                        {
                            Code = "330106",
                            CreatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 437, DateTimeKind.Utc).AddTicks(1305),
                            IsDeleted = false,
                            Level = 2,
                            Name = "西湖区",
                            ParentCode = "330100",
                            UpdatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 437, DateTimeKind.Utc).AddTicks(1304)
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.ReviewAllocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("ExpertId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("NodeId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("TaskId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("review_allocations");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AssignedAt = new DateTime(2025, 12, 10, 7, 52, 15, 495, DateTimeKind.Utc).AddTicks(3324),
                            CreatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 495, DateTimeKind.Utc).AddTicks(2785),
                            ExpertId = 100L,
                            IsDeleted = false,
                            NodeId = 3L,
                            Status = 0,
                            TaskId = 1L,
                            UpdatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 495, DateTimeKind.Utc).AddTicks(2785)
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.ScoringModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("scoring_templates");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 481, DateTimeKind.Utc).AddTicks(566),
                            IsDeleted = false,
                            Name = "通用四级评分标准(A/B/C/D)",
                            UpdatedAt = new DateTime(2025, 12, 10, 15, 52, 15, 480, DateTimeKind.Local).AddTicks(9914)
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.ScoringModelItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LevelCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("Ratio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("ScoringModelId")
                        .HasColumnType("bigint");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<long>("TemplateId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ScoringModelId");

                    b.ToTable("scoring_template_items");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 482, DateTimeKind.Utc).AddTicks(1011),
                            Description = "完全符合指标要求，佐证材料详实",
                            IsDeleted = false,
                            LevelCode = "A",
                            Ratio = 1.0m,
                            Sort = 1,
                            TemplateId = 1L,
                            UpdatedAt = new DateTime(2025, 12, 10, 15, 52, 15, 482, DateTimeKind.Local).AddTicks(309)
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 482, DateTimeKind.Utc).AddTicks(1100),
                            Description = "基本符合，存在少量非关键性缺失",
                            IsDeleted = false,
                            LevelCode = "B",
                            Ratio = 0.8m,
                            Sort = 2,
                            TemplateId = 1L,
                            UpdatedAt = new DateTime(2025, 12, 10, 15, 52, 15, 482, DateTimeKind.Local).AddTicks(1097)
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 482, DateTimeKind.Utc).AddTicks(1102),
                            Description = "部分符合，存在明显问题或材料不足",
                            IsDeleted = false,
                            LevelCode = "C",
                            Ratio = 0.6m,
                            Sort = 3,
                            TemplateId = 1L,
                            UpdatedAt = new DateTime(2025, 12, 10, 15, 52, 15, 482, DateTimeKind.Local).AddTicks(1101)
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 482, DateTimeKind.Utc).AddTicks(1104),
                            Description = "不符合要求或未开展此项工作",
                            IsDeleted = false,
                            LevelCode = "D",
                            Ratio = 0.0m,
                            Sort = 4,
                            TemplateId = 1L,
                            UpdatedAt = new DateTime(2025, 12, 10, 15, 52, 15, 482, DateTimeKind.Local).AddTicks(1103)
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.SpeEvalNode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Depth")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("MaxScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Path")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<long?>("ScoringTemplateId")
                        .HasColumnType("bigint");

                    b.Property<long>("TreeId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("spe_eval_nodes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 484, DateTimeKind.Utc).AddTicks(2818),
                            Depth = 0,
                            IsDeleted = false,
                            MaxScore = 100m,
                            Name = "河北省特教评价2025",
                            OrderIndex = 0,
                            Path = "0",
                            TreeId = 202501L,
                            Type = 0,
                            UpdatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 484, DateTimeKind.Utc).AddTicks(2820)
                        },
                        new
                        {
                            Id = 2L,
                            Code = "1",
                            CreatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 484, DateTimeKind.Utc).AddTicks(3835),
                            Depth = 1,
                            IsDeleted = false,
                            MaxScore = 20m,
                            Name = "办学方向",
                            OrderIndex = 0,
                            ParentId = 1L,
                            Path = "0,1",
                            TreeId = 202501L,
                            Type = 1,
                            UpdatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 484, DateTimeKind.Utc).AddTicks(3835)
                        },
                        new
                        {
                            Id = 3L,
                            Code = "1.1",
                            CreatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 484, DateTimeKind.Utc).AddTicks(3924),
                            Depth = 2,
                            IsDeleted = false,
                            MaxScore = 5m,
                            Name = "坚持办学方向",
                            OrderIndex = 0,
                            ParentId = 2L,
                            Path = "0,1,2",
                            ScoringTemplateId = 1L,
                            TreeId = 202501L,
                            Type = 4,
                            UpdatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 484, DateTimeKind.Utc).AddTicks(3925)
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.SysRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("remark")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("sys_role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ADMIN",
                            CreatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 503, DateTimeKind.Utc).AddTicks(5666),
                            IsDeleted = false,
                            Name = "管理员",
                            Sort = 1,
                            UpdatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 503, DateTimeKind.Utc).AddTicks(5762),
                            remark = "系统超级管理员"
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.SysUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Account")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("OrgId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("User_type")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("sys_user");
                });

            modelBuilder.Entity("Tsjy.Core.Entities.SysUsers", b =>
                {
                    b.Property<string>("IDNumber")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("OrgId")
                        .HasColumnType("int");

                    b.Property<int>("OrgType")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<string>("RealName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserName")
                        .HasColumnType("varchar(255)");

                    b.HasKey("IDNumber");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("sys_users");

                    b.HasData(
                        new
                        {
                            IDNumber = "123456789012345678",
                            CreatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 511, DateTimeKind.Utc).AddTicks(6530),
                            IsDeleted = false,
                            OrgId = 1,
                            OrgType = 2,
                            Password = "7C4A8D09CA3762AF61E59520943DC26494F8941B",
                            Phone = "13800000000",
                            RealName = "超级管理员",
                            Role = 0,
                            UpdatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 511, DateTimeKind.Utc).AddTicks(6639),
                            UserName = "admin"
                        },
                        new
                        {
                            IDNumber = "123456789012345679",
                            CreatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 511, DateTimeKind.Utc).AddTicks(6846),
                            IsDeleted = false,
                            OrgId = 1,
                            OrgType = 2,
                            Password = "7C4A8D09CA3762AF61E59520943DC26494F8941B",
                            Phone = "13800000000",
                            RealName = "超级管理员",
                            Role = 0,
                            UpdatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 511, DateTimeKind.Utc).AddTicks(6847),
                            UserName = "100"
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.Tasks", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("BatchId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DueAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("FinalScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("TargetId")
                        .HasColumnType("bigint");

                    b.Property<int>("TargetType")
                        .HasColumnType("int");

                    b.Property<long>("TreeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("tasks");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BatchId = 1L,
                            CreatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 516, DateTimeKind.Utc).AddTicks(6172),
                            DueAt = new DateTime(2025, 12, 17, 7, 52, 15, 516, DateTimeKind.Utc).AddTicks(6088),
                            IsDeleted = false,
                            StartAt = new DateTime(2025, 12, 10, 7, 52, 15, 516, DateTimeKind.Utc).AddTicks(5997),
                            Status = 2,
                            TargetId = 1L,
                            TargetType = 0,
                            TreeId = 202501L,
                            UpdatedAt = new DateTime(2025, 12, 10, 7, 52, 15, 516, DateTimeKind.Utc).AddTicks(5448)
                        });
                });

            modelBuilder.Entity("Tsjy.Core.Entities.ScoringModelItem", b =>
                {
                    b.HasOne("Tsjy.Core.Entities.ScoringModel", null)
                        .WithMany("Items")
                        .HasForeignKey("ScoringModelId");
                });

            modelBuilder.Entity("Tsjy.Core.Entities.ScoringModel", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
